export const DERIVE = ['deriveBits', 'deriveKey']
export const WRAP = ['wrapKey', 'unwrapKey']
export const ENCRYPT = ['encrypt', 'decrypt']
export const SIGN = ['sign', 'verify']
export const VERIFY_ONLY = ['verify']
export const ENCRYPT_ONLY = ['encrypt']
